bases: 
  - ../app
patches:
  - image.yaml
configMapGenerator:
  - name: config
    behavior: replace
    # envs: 
    #   - config/.env
    # files:
    #   - config/config.yaml
    literals:
      - username=gtk
      - password=secret